# -*- coding: utf-8 -*-
"""
stamp_build.py
Writes utils/_build_stamp.txt with the commit the build came from.

Why this exists: a frozen PyInstaller build (and a Docker image) has no .git,
so utils/branding.py cannot discover its own build number. The build scripts
run this first, and the generated file — bundled via --add-data "utils;utils" —
becomes the fallback.

Running from source you never need this: branding.py reads the live .git and
always reports the commit you are actually on, so the build number changes by
itself with every commit.

    python build_scripts/stamp_build.py
"""

import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STAMP = os.path.join(ROOT, "utils", "_build_stamp.txt")


def git(*args):
    """Run a git command in the project root; return stdout or '' on any failure."""
    try:
        result = subprocess.run(["git", *args], cwd=ROOT, capture_output=True, text=True, timeout=10)
    except (OSError, subprocess.SubprocessError):
        return ""
    return result.stdout.strip() if result.returncode == 0 else ""


def main():
    commit = git("rev-parse", "--short", "HEAD")

    if not commit:
        print(
            "WARNING: no git commit found — the packaged build will report 'dev' as its build number.",
            file=sys.stderr,
        )

    with open(STAMP, "w", encoding="utf-8") as fh:
        fh.write("# Generated by build_scripts/stamp_build.py — do not edit or commit.\n")
        fh.write(f"commit={commit}\n")

    print(f"Stamped build number: {commit or 'dev'}")
    print(f"  -> {os.path.relpath(STAMP, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
